[package]
name = "yas-derive-wuthering-waves"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["parsing"] }
quote = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"