name: Branch modification

on:
  push:
    branches:
      - modification
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For $commitCount
          lfs: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Extract git-rev
        run: |
          $commitCount = git rev-list --count HEAD
          $shortHash = git rev-parse --short HEAD
          "GIT_REV=r$commitCount.$shortHash" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Setup Toolchain
        run: rustup default nightly-msvc

      - name: Set version in Cargo.toml
        run: |
          $files = @(
              './Cargo.toml'
              './yas/Cargo.toml'
              './yas-genshin/Cargo.toml'
              './yas-starrail/Cargo.toml'
          )
          [regex]$pattern = '(?<=version = ").*(?=")'
          foreach ($file in $files) {
              $pattern.Replace((Get-Content -Raw $file), "0.0.0-$env:GIT_REV", 1) | Out-File -FilePath $file
          }

      - name: Build (Release)
        run: cargo build --release

      - name: Rename Outputs
        run: |
          Move-Item ./target/release/yas_scanner_genshin.exe "yas_scanner_genshin_$env:GIT_REV.exe"
          Move-Item ./target/release/yas_scanner_starrail.exe "yas_scanner_starrail_$env:GIT_REV.exe"

      - name: Upload yas_scanner_genshin
        uses: actions/upload-artifact@v4
        with:
          name: yas_scanner_genshin_${{ env.GIT_REV }}
          path: yas_scanner_genshin_${{ env.GIT_REV }}.exe

      - name: Upload yas_scanner_starrail
        uses: actions/upload-artifact@v4
        with:
          name: yas_scanner_starrail_${{ env.GIT_REV }}
          path: yas_scanner_starrail_${{ env.GIT_REV }}.exe

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Toolchain
        run: rustup default nightly

      - name: Check
        run: cargo check

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Toolchain
        run: rustup default nightly

      - name: Check
        run: cargo check
